# Generated by Django 4.2.4 on 2023-10-18 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('STUDENT', 'Student')], default='EMPLOYEE', max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(default='2004-04-25')),
                ('contact', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1000000000), django.core.validators.MaxValueValidator(limit_value=9999999999)])),
                ('hostel', models.CharField(blank=True, choices=[('ht1', 'Aryabhatta'), ('ht2', 'Dhanrajgiri 1'), ('ht3', 'Dhanrajgiri 2'), ('ht4', 'Vishwesaraiya'), ('ht5', 'SN Bose'), ('ht6', 'Satish Dhawan'), ('ht7', 'Morvi 1'), ('ht8', 'Morvi 2'), ('ht9', 'CV Raman'), ('ht10', 'Rajputana'), ('ht11', 'Limbdi'), ('ht12', 'New Girls'), ('ht13', 'Old Girls')], max_length=100)),
                ('branch', models.CharField(blank=True, choices=[('cse', 'Computer Science and Engineering'), ('mnc', 'Mathematics and Computation'), ('ece', 'Electronics and Communication Engineering'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('chem', 'Chemical Engineering'), ('cer', 'Ceramic Engineering'), ('civ', 'Civil Engineering'), ('mat', 'Material Science'), ('phe', 'Pharmaceutical Engineering'), ('min', 'Mining'), ('ic', 'Industrial Chemistry')], max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
