# Generated by Django 4.2.4 on 2023-10-20 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='purchased_from',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('sold_to', models.IntegerField()),
                ('sold_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
