# Generated by Django 4.2.4 on 2023-10-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_purchased_purchased_from_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
